/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appCliente;

import datos.Configuracion;
import datos.Correo;
import datos.Cuenta;
import datos.Protocolo;
import datos.Servicio;
import facade.IMailSender;
import facade.MailSenderFacade;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Dell
 */
public class FrmConfiguracion extends javax.swing.JFrame {

    private IMailSender mailSender;
    private Configuracion configuracionCreada;
    private Configuracion configuracionDisponible;
    private DefaultComboBoxModel servicios;
    
    /**
     * Creates new form FrmConfiguracion
     */
    public FrmConfiguracion() {
        initComponents();
        mailSender = new MailSenderFacade();
        cmbxServicio.removeAllItems();
        cmbxProtocolo.removeAllItems();
        cmbxCuenta.removeAllItems();
        btnEnviar.setEnabled(false);
        configuracionDisponible = null;
        configuracionDisponible = mailSender.consultarConfiguracion();
        llenarCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        cmbxServicio = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        lblInstruccion = new javax.swing.JLabel();
        lblServicio = new javax.swing.JLabel();
        lblProtocolo = new javax.swing.JLabel();
        lblCuenta = new javax.swing.JLabel();
        cmbxProtocolo = new javax.swing.JComboBox<>();
        cmbxCuenta = new javax.swing.JComboBox<>();
        btnConfirmar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitulo2 = new javax.swing.JLabel();
        lblConcepto = new javax.swing.JLabel();
        txtfldConcepto = new javax.swing.JTextField();
        lblDestinatario = new javax.swing.JLabel();
        txtfldDestinatario = new javax.swing.JTextField();
        lblCuerpo = new javax.swing.JLabel();
        txtfldCuerpo = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        lblInstruccion2 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbxServicio.setModel(servicios);
        cmbxServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxServicioActionPerformed(evt);
            }
        });

        lblTitulo.setText("Configuración");

        lblInstruccion.setText("Seleccione la configuración para el correo:");

        lblServicio.setText("Servicio:");

        lblProtocolo.setText("Protocolo:");

        lblCuenta.setText("Cuenta:");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblTitulo2.setText("Nuevo correo");

        lblConcepto.setText("Concepto:");

        txtfldConcepto.setEditable(false);

        lblDestinatario.setText("Destinatario:");

        txtfldDestinatario.setEditable(false);

        lblCuerpo.setText("Cuerpo:");

        txtfldCuerpo.setEditable(false);
        txtfldCuerpo.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        lblInstruccion2.setText("Primero, no olvide escoger una configuración.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblInstruccion)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConfirmar)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo2)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEnviar)
                        .addGap(164, 164, 164))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(lblServicio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbxServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblProtocolo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbxProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(lblCuenta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbxCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDestinatario)
                                .addComponent(lblConcepto)
                                .addComponent(lblCuerpo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtfldCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfldConcepto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                    .addComponent(txtfldDestinatario, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(lblInstruccion2)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruccion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblServicio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbxServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblProtocolo)
                        .addComponent(cmbxProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuenta)
                    .addComponent(cmbxCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstruccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfldDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestinatario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfldConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConcepto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfldCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCuerpo))
                .addGap(18, 18, 18)
                .addComponent(btnEnviar)
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        configuracionCreada = null;
        Protocolo protocoloSeleccionado = new Protocolo(cmbxProtocolo.getSelectedItem().toString());
        List<Protocolo> listaProtocolos = new LinkedList<>();
        listaProtocolos.add(protocoloSeleccionado);
        Cuenta cuentaSeleccionada = new Cuenta(cmbxCuenta.getSelectedItem().toString());
        List<Cuenta> listaCuentas = new LinkedList<>();
        listaCuentas.add(cuentaSeleccionada);
        Servicio servicioSeleccionado = new Servicio(cmbxServicio.getSelectedItem().toString());
        servicioSeleccionado.setProtocolos(listaProtocolos);
        servicioSeleccionado.setCuentas(listaCuentas);
        List<Servicio> listaServicios = new LinkedList<>();
        configuracionCreada.setServicios(listaServicios);
        
        txtfldDestinatario.setEditable(true);
        txtfldConcepto.setEditable(true);
        txtfldCuerpo.setEditable(true);
        btnEnviar.setEnabled(true);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String destinatario = txtfldDestinatario.getText();
        String concepto = txtfldConcepto.getText();
        String cuerpo = txtfldCuerpo.getText();
        
        Correo correoNuevo = new Correo(destinatario, concepto, cuerpo);
        
        mailSender.enviarCorreo(correoNuevo, configuracionCreada);
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void cmbxServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxServicioActionPerformed
        llenarCombobox();
    }//GEN-LAST:event_cmbxServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConfiguracion().setVisible(true);
            }
        });
    }
    
    private void llenarCombobox() {
        List<Servicio> servicios = new LinkedList<>();
        servicios = configuracionDisponible.getServicios();

        for (Servicio servicio : servicios) {
            cmbxServicio.addItem(servicio);
        }

        Servicio servicio = (Servicio) cmbxServicio.getSelectedItem();
        
        for (Protocolo protocolo : servicio.getProtocolos()) {
            cmbxProtocolo.addItem(protocolo.getNombre());
        }

        for (Cuenta cuenta : servicio.getCuentas()) {
            cmbxCuenta.addItem(cuenta.getDireccion());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> cmbxCuenta;
    private javax.swing.JComboBox<String> cmbxProtocolo;
    private javax.swing.JComboBox<String> cmbxServicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblConcepto;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblCuerpo;
    private javax.swing.JLabel lblDestinatario;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblInstruccion2;
    private javax.swing.JLabel lblProtocolo;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTextField txtfldConcepto;
    private javax.swing.JTextField txtfldCuerpo;
    private javax.swing.JTextField txtfldDestinatario;
    // End of variables declaration//GEN-END:variables
}
